# -*- coding: utf-8 -*-
"""Comprehensive Islamic Studies question pools."""

def q(skill, difficulty, prompt, options, correct, audience="both"):
    return dict(skill=skill, difficulty=difficulty, prompt=prompt, options=options,
                correct=correct, audience=audience, arabic=None)


# ===========================================================================
# STAGE 1 - Basic Islamic Knowledge   (kids L1)
# Skills: Pillars & Practice | Belief | Prayer | Qur'an & Hadith | Manners & Du'a
# ===========================================================================
IC_S1 = [
    # ---- easy ----
    q("Pillars & Practice", "easy",
      "How many pillars of Islam are there?",
      ["Three", "Four", "Five", "Six"],
      2),
    q("Belief", "easy",
      "How many pillars of iman (belief) are there?",
      ["Six", "Five", "Four", "Seven"],
      0, "kids"),
    q("Prayer", "easy",
      "Which of these is one of the five daily prayers?",
      ["Istikharah", "Witr", "Tarawih", "Asr"],
      3),
    q("Prayer", "easy",
      "Which prayer is prayed just after the sun sets?",
      ["Fajr", "Maghrib", "Asr", "Isha"],
      1, "kids"),
    q("Qur'an & Hadith", "easy",
      "What is the Qur'an?",
      ["The teachings of the scholars of the past",
       "The sayings of the friends of the Prophet",
       "The words of Allah sent to His Prophet",
       "The stories of the tribes of the Arabs"],
      2),
    q("Manners & Du'a", "easy",
      "What does a Muslim say before beginning to eat?",
      ["Astaghfirullah", "Alhamdulillah", "Subhan Allah", "Bismillah"],
      3, "kids"),
    q("Pillars & Practice", "easy",
      "Fasting for a whole month is required of Muslims in which month?",
      ["Ramadan", "Shawwal", "Muharram", "Rajab"],
      0),
    # ---- medium ----
    q("Prayer", "medium",
      "Aisha wakes up late and the time for Fajr has already finished. What should she do?",
      ["Pray it twice the next morning",
       "Pray it as soon as she remembers",
       "Leave it and pray Dhuhr instead",
       "Give charity in place of it"],
      1, "kids"),
    q("Prayer", "medium",
      "Bilal made wudu, then used the bathroom before he prayed. What must he do?",
      ["Wait for the next prayer time",
       "Pray without repeating anything",
       "Wash only his hands and face",
       "Make wudu again before praying"],
      3),
    q("Pillars & Practice", "medium",
      "The daily fast of Ramadan lasts from which time to which time?",
      ["From dawn until nightfall",
       "From sunrise until sunset",
       "From dawn until sunset",
       "From midnight until sunrise"],
      2, "adults"),
    q("Pillars & Practice", "medium",
      "A boy who is fasting eats a biscuit by mistake, forgetting the fast. What should he do?",
      ["Break the fast and begin again tomorrow",
       "Carry on fasting for the rest of the day",
       "Make up two days after Ramadan ends",
       "Give food to a poor person that day"],
      1, "kids"),
    q("Belief", "medium",
      "Which statement about the angels is correct?",
      ["They always obey what Allah commands them",
       "They were made from clay like human beings",
       "They are seen by people in daily life",
       "They were sent as messengers to nations"],
      0),
    q("Qur'an & Hadith", "medium",
      "What is a hadith?",
      ["A report of the Prophet's words or actions",
       "A chapter taken from the Book of Allah",
       "A du'a said after the daily prayers",
       "A ruling written by the later scholars"],
      0),
    q("Manners & Du'a", "medium",
      "Fatimah's friend gives her a gift. Which of these is the best thing for her to say?",
      ["All praise belongs to Allah alone",
       "Glory be to Allah the Most High",
       "I seek the forgiveness of Allah",
       "May Allah reward you with good"],
      3, "kids"),
    q("Manners & Du'a", "medium",
      "A Muslim hears that a relative has passed away. What does he say?",
      ["In the name of Allah, the Most Merciful",
       "To Allah we belong and to Him we return",
       "There is no might except with Allah",
       "Allah is enough for me, and He is the best"],
      1, "adults"),
    q("Prayer", "medium",
      "A man at work has a short break for Dhuhr and has no prayer mat with him. What should he do?",
      ["Give charity instead of praying then",
       "Delay the prayer until he gets home",
       "Pray on any clean place he can find",
       "Ask a colleague to pray it for him"],
      2, "adults"),
    q("Belief", "medium",
      "Which statement matches what Muslims believe about the prophets?",
      ["Only the Arabs were sent messengers",
       "Allah sent messengers to every nation",
       "The prophets knew all of the unseen",
       "The prophets were angels in human form"],
      1, "adults"),
    q("Pillars & Practice", "medium",
      "Zakah is wealth that is given to which people?",
      ["The poor and those in need",
       "The wealthy of the community",
       "Only the closest family members",
       "Anyone who asks in the masjid"],
      0, "adults"),
    # ---- hard ----
    q("Pillars & Practice", "hard",
      "A man is on a long journey in Ramadan and finds fasting very hard. What is he allowed to do?",
      ["Pay money instead of the missed days",
       "Fast half of the day and then eat",
       "Break it and make up the days later",
       "Fast on every second day of the month"],
      2, "adults"),
    q("Prayer", "hard",
      "Musa's mother calls him while he is praying an obligatory prayer. What should he do?",
      ["Leave it and pray it again later",
       "Stop praying at once and answer",
       "Answer quietly and keep praying",
       "Finish the prayer, then answer her"],
      3, "kids"),
    q("Qur'an & Hadith", "hard",
      "Which statement correctly compares the Qur'an and the hadith?",
      ["The Qur'an was written by the companions from memory",
       "Both of them are Allah's own speech revealed the same way",
       "The hadith came first and the Qur'an explained them",
       "The Qur'an is Allah's speech; hadith are the Prophet's words"],
      3),
    q("Manners & Du'a", "hard",
      "A guest arrives at a Muslim's home at meal time without warning. What does the Prophet's "
      "guidance teach?",
      ["Ask the guest to return another day",
       "Honour the guest and share the food",
       "Eat first and then greet the guest",
       "Give the guest money to buy food"],
      1, "adults"),
    q("Belief", "hard",
      "A man is asked why he still prays carefully when he is alone at home. Which belief best "
      "explains it?",
      ["Allah sees everything, even in private",
       "The angels record only public worship",
       "Prayer at home replaces the masjid",
       "Worship done alone earns double reward"],
      0, "adults"),
    q("Pillars & Practice", "hard",
      "Sara's family gives part of their savings to poor neighbours each year. Which pillar of "
      "Islam is this?",
      ["Sawm", "Salah", "Zakah", "Hajj"],
      2, "kids"),
    # ---- added: audience balance ----
    q("Manners & Du'a", "easy",
      "What does a Muslim say when he meets another Muslim?",
      ["Jazak Allahu khayran", "As-salamu alaykum", "Subhan Allah", "Ma sha Allah"],
      1, "kids"),
    q("Prayer", "easy",
      "Which surah is recited in every rak'ah of the prayer?",
      ["Surah al-Ikhlas", "Surah an-Nas", "Surah al-Fatihah", "Surah al-Falaq"],
      2, "kids"),
    q("Pillars & Practice", "easy",
      "Which pillar of Islam is performed once in a lifetime by those who are able?",
      ["Hajj", "Zakah", "Sawm", "Salah"],
      0, "adults"),
    q("Belief", "medium",
      "What do the two angels who are with every person do?",
      ["They choose what he will do",
       "They decide when he sleeps",
       "They teach him what to say",
       "They write down what he does"],
      3, "kids"),
    q("Prayer", "medium",
      "The adhan is called out to announce what?",
      ["That the imam has now arrived",
       "That the masjid door is open",
       "That a prayer time has begun",
       "That the khutbah has ended"],
      2, "adults"),
    q("Qur'an & Hadith", "medium",
      "What is a Muslim taught to say before he begins reciting the Qur'an?",
      ["I bear witness that Allah is only one",
       "I seek refuge with Allah from Shaytan",
       "I ask Allah to forgive my many sins",
       "I praise Allah for His many gifts"],
      1, "adults"),
    q("Prayer", "hard",
      "Hana reaches the masjid and finds the congregation already praying. What should she do?",
      ["Wait until the imam has finished",
       "Join the prayer where it is now",
       "Start her own prayer beside them",
       "Pray after everyone has left"],
      1, "kids"),
    q("Belief", "hard",
      "Someone asks why Muslims never make an image of Allah. Which belief explains this?",
      ["Nothing in the creation is like Him",
       "Images are too hard to draw well",
       "Only the prophets may be pictured",
       "He will be seen by all in this life"],
      0, "adults"),
]

# ===========================================================================
# STAGE 2 - Belief & Worship Foundations   (kids L2, adults L1)
# Skills: Tawheed & Belief | Angels & Books | Prophets | Worship | Seerah
# ===========================================================================
IC_S2 = [
    # ---- easy ----
    q("Tawheed & Belief", "easy",
      "What does the word tawheed mean?",
      ["Purifying wealth by giving charity",
       "Following the Sunnah in every act",
       "Singling out Allah alone in worship",
       "Reciting the Qur'an with its rules"],
      2),
    q("Angels & Books", "easy",
      "Which angel brought the revelation to the prophets?",
      ["Jibreel", "Mika'il", "Israfil", "Malik"],
      0, "kids"),
    q("Angels & Books", "easy",
      "Which book was revealed to Prophet Musa?",
      ["The Furqan", "The Injeel", "The Zaboor", "The Tawrah"],
      3, "kids"),
    q("Worship", "easy",
      "The qiblah that Muslims face in prayer is towards which place?",
      ["The Prophet's masjid in Madinah",
       "The Ka'bah in the city of Makkah",
       "The cave of the first revelation",
       "The mount where Musa was spoken to"],
      1, "kids"),
    q("Seerah", "easy",
      "The Hijrah was the migration of the Muslims from which city to which city?",
      ["From Makkah to Abyssinia",
       "From Madinah to Makkah",
       "From Makkah to Madinah",
       "From Madinah to Ta'if"],
      2, "kids"),
    q("Seerah", "easy",
      "Where was the Prophet when the first revelation came to him?",
      ["Inside the Ka'bah in the city of Makkah",
       "In the masjid of the city of Madinah",
       "On the plain of Arafah outside Makkah",
       "In the cave of Hira outside Makkah"],
      3),
    q("Worship", "easy",
      "What share of saved wealth is given as zakah once it is due?",
      ["2.5 percent", "5 percent", "10 percent", "20 percent"],
      0, "adults"),
    # ---- medium ----
    q("Angels & Books", "medium",
      "From what were the angels created, and how do they act?",
      ["From fire, and some of them disobey Allah",
       "From light, and they never disobey Allah",
       "From clay, and they were sent as prophets",
       "From water, and they live among people"],
      1),
    q("Angels & Books", "medium",
      "Which book was given to Prophet Dawud?",
      ["The Suhuf", "The Tawrah", "The Injeel", "The Zaboor"],
      3, "kids"),
    q("Prophets", "medium",
      "What must a Muslim believe about Prophet Isa?",
      ["He was an angel in a human form",
       "He was the son of Allah Most High",
       "He was a human messenger of Allah",
       "He was the last of the messengers"],
      2, "kids"),
    q("Prophets", "medium",
      "Which statement about the messengers of Allah is correct?",
      ["Each one of them brought a different religion",
       "They all called their people to worship Allah alone",
       "They were chosen from among the angels of Allah",
       "They were given knowledge of all of the unseen"],
      1),
    q("Worship", "medium",
      "How does a recommended (sunnah) act differ from an obligatory act?",
      ["No sin is taken for leaving it",
       "It earns no reward when it is done",
       "It may only be done in Ramadan",
       "It applies to men and not to women"],
      0),
    q("Worship", "medium",
      "Which of these breaks the fast of a person fasting in Ramadan?",
      ["Eating on purpose during the day",
       "Cleaning the teeth with a miswak",
       "Taking a shower to cool down",
       "Smelling the food while cooking"],
      0, "kids"),
    q("Worship", "medium",
      "A traveller in an unfamiliar city cannot tell which way the qiblah is. What should he do?",
      ["Delay the prayer until he gets home",
       "Wait until somebody tells him the way",
       "Pray in any direction and repeat later",
       "Work out the direction as best he can"],
      3, "adults"),
    q("Seerah", "medium",
      "The first revelation to the Prophet began with a command to do what?",
      ["Fight", "Read", "Migrate", "Fast"],
      1),
    q("Seerah", "medium",
      "Why did the Prophet and the Muslims leave Makkah for Madinah?",
      ["They were looking for more farmland",
       "They wanted better trade in Madinah",
       "They were harmed there for their faith",
       "They were following a yearly custom"],
      2, "kids"),
    q("Tawheed & Belief", "medium",
      "A woman meets serious difficulty and turns to Allah alone for help. Which belief is she "
      "acting on?",
      ["Hardship is a sign of Allah's anger",
       "Allah alone controls benefit and harm",
       "Du'a is answered only after prayer",
       "Patience removes the need for du'a"],
      1, "adults"),
    q("Tawheed & Belief", "medium",
      "Belief in the Last Day means a Muslim believes that:",
      ["people will be raised and judged by Allah",
       "the world will carry on without any end",
       "only the prophets will be brought back",
       "deeds are all repaid within this life"],
      0),
    # ---- hard ----
    q("Worship", "hard",
      "Who is excused from fasting Ramadan but must make up the missed days afterwards?",
      ["A person with a permanent illness",
       "An elderly man who can never fast",
       "A woman during her monthly period",
       "A child who has not yet reached puberty"],
      2, "adults"),
    q("Worship", "hard",
      "A man usually prays two sunnah rak'ahs before Fajr, but one morning he misses them. What is "
      "the ruling?",
      ["He must give charity for missing them",
       "He must make them up before Dhuhr",
       "He has left an obligation of prayer",
       "He has taken no sin for missing them"],
      3, "adults"),
    q("Tawheed & Belief", "hard",
      "Which of these best shows tawheed in a person's daily life?",
      ["He learns the Qur'an in Arabic alone",
       "He prays only in the month of Ramadan",
       "He gives his charity where others see",
       "He asks Allah alone to fulfil his needs"],
      3),
    q("Prophets", "hard",
      "Someone claims that a new prophet has been sent after Muhammad. What is the correct belief?",
      ["A prophet may come in every century",
       "No prophet will come after Muhammad",
       "Only messengers, not prophets, ended",
       "Prophethood ends when Isa returns"],
      1, "adults"),
    q("Angels & Books", "hard",
      "What must a Muslim believe about the earlier revealed books?",
      ["They were true when Allah revealed them",
       "They are read today just as they came",
       "They were sent down to the angels first",
       "They carry the same laws as the Qur'an"],
      0),
    q("Seerah", "hard",
      "Why is the Hijrah important enough to begin the Islamic calendar?",
      ["It was when the Qur'an was fully completed",
       "It was the year in which the Prophet was born",
       "The Muslims could build their own community",
       "It ended every dispute among the Arab tribes"],
      2, "adults"),
    # ---- added: audience balance ----
    q("Prophets", "easy",
      "Which prophet raised the Ka'bah together with his son Isma'il?",
      ["Nuh", "Musa", "Ibrahim", "Isa"],
      2, "kids"),
    q("Worship", "easy",
      "Which prayer do Muslims pray in congregation every Friday?",
      ["Jumu'ah", "Tarawih", "Eid", "Witr"],
      0, "kids"),
    q("Tawheed & Belief", "medium",
      "A child is asked who gives people their food and their life. What is the right answer?",
      ["The angels provide them",
       "Hard work provides them",
       "Allah alone provides them",
       "The prophets provide them"],
      2, "kids"),
    q("Worship", "medium",
      "Which of these is required for the fast of Ramadan to be valid?",
      ["Praying tarawih each night",
       "Making the intention to fast",
       "Eating suhoor before dawn",
       "Reciting the whole Qur'an"],
      1, "adults"),
    q("Seerah", "medium",
      "In the Prophet's time, who were the Ansar?",
      ["The Muslims who left Makkah",
       "The people of Madinah who helped",
       "The tribes who fought the Muslims",
       "The traders who visited the city"],
      1, "adults"),
    q("Prophets", "hard",
      "Which quality must every prophet of Allah have?",
      ["Knowledge of all future events",
       "Power to answer people's du'a",
       "Freedom from every human need",
       "Truthfulness in what they convey"],
      3, "adults"),
    q("Tawheed & Belief", "hard",
      "A man has sinned greatly and asks whether Allah will accept his repentance. What is correct?",
      ["Sins are removed by charity alone",
       "Repentance is accepted only once",
       "Allah forgives whoever turns to Him",
       "Only the prophets can be forgiven"],
      2, "adults"),
]

# ===========================================================================
# STAGE 3 - Understanding the Islamic Sciences   (kids L3, adults L2)
# Skills: Tawheed & Qadar | Qur'an Sciences | Hadith Sciences | Fiqh & Zakah | Manners & Family
# ===========================================================================
IC_S3 = [
    # ---- easy ----
    q("Tawheed & Qadar", "easy",
      "Tawheed ar-rububiyyah is singling out Allah in which matter?",
      ["His beautiful names and attributes",
       "The worship that is offered to Him",
       "His lordship over the creation",
       "The laws He revealed to the people"],
      2),
    q("Qur'an Sciences", "easy",
      "A surah revealed after the Hijrah is described as:",
      ["Madani", "Makki", "Muhkam", "Mufassal"],
      0, "kids"),
    q("Hadith Sciences", "easy",
      "In a hadith, what is the isnad?",
      ["The book in which it was recorded",
       "The wording of what the Prophet said",
       "The ruling that scholars took from it",
       "The chain of people who reported it"],
      3, "kids"),
    q("Hadith Sciences", "easy",
      "In a hadith, what is the matn?",
      ["The narrators who passed it along",
       "The actual text that was reported",
       "The grade the scholars gave to it",
       "The chapter it was placed under"],
      1),
    q("Fiqh & Zakah", "easy",
      "What does the nisab mean in the rules of zakah?",
      ["The time of year that zakah is collected",
       "The share of the wealth that is paid out",
       "The least wealth at which zakah is due",
       "The people who are given the zakah money"],
      2),
    q("Manners & Family", "easy",
      "What does birr al-walidayn refer to?",
      ["Honouring the teachers and elders",
       "Keeping ties with all the relatives",
       "Supporting the poor of the family",
       "Being dutiful and kind to parents"],
      3, "kids"),
    q("Qur'an Sciences", "easy",
      "Asbab an-nuzul is the study of what?",
      ["The events surrounding a verse's revelation",
       "The rules for reciting the Qur'an correctly",
       "The gathering of the Qur'an into one book",
       "The differences between the known readings"],
      0),
    # ---- medium ----
    q("Tawheed & Qadar", "medium",
      "A man accepts that Allah alone created everything, yet he directs acts of worship to others. "
      "Which category of tawheed has he broken?",
      ["Rububiyyah", "Uluhiyyah", "Asma' wa Sifat", "Qadar"],
      1, "adults"),
    q("Tawheed & Qadar", "medium",
      "Which statement belongs to tawheed al-asma' was-sifat?",
      ["Allah sent messengers to guide each of the nations",
       "Allah alone deserves every act of worship",
       "Allah alone created and sustains the whole world",
       "Allah hears and sees in a way suited to Him"],
      3),
    q("Tawheed & Qadar", "medium",
      "Belief in al-qadar includes believing that:",
      ["some events happen outside Allah's knowledge",
       "people carry out their acts with no choice",
       "Allah knew all things before creating them",
       "the future may be read from the stars"],
      2, "kids"),
    q("Qur'an Sciences", "medium",
      "Madani surahs generally deal more with which subjects?",
      ["The oneness of Allah and the hereafter",
       "Laws and the life of the community",
       "The stories of the earlier nations",
       "Warnings given to the tribes of Makkah"],
      1, "adults"),
    q("Qur'an Sciences", "medium",
      "How does knowing asbab an-nuzul help a reader of the Qur'an?",
      ["It clarifies the meaning a verse intends",
       "It gives the number of verses in a surah",
       "It proves the chain of reciters is sound",
       "It fixes the order of surahs in the mushaf"],
      0),
    q("Hadith Sciences", "medium",
      "A hadith is graded da'if when:",
      ["a condition of authenticity is missing",
       "its meaning is difficult to understand",
       "only one companion reported it to us",
       "it is not found in Sahih al-Bukhari"],
      0),
    q("Hadith Sciences", "medium",
      "Why did the scholars study the lives of the narrators of hadith?",
      ["To decide the order of the chapters",
       "To count how many hadith they knew",
       "To learn which cities they lived in",
       "To check their memory and honesty"],
      3, "kids"),
    q("Fiqh & Zakah", "medium",
      "A man's savings have been above the nisab for six months. Is zakah due on them now?",
      ["Yes, half of the yearly amount is due",
       "No, not until a full lunar year passes",
       "Yes, because the nisab has been reached",
       "No, zakah is due on gold and silver only"],
      1, "adults"),
    q("Manners & Family", "medium",
      "An adult's father asks him to do something he dislikes, though there is nothing wrong with "
      "it. What should he do?",
      ["Obey only if his father insists twice",
       "Refuse politely and explain his view",
       "Obey, as no sin is involved in it",
       "Ask a scholar before doing anything"],
      2, "adults"),
    q("Manners & Family", "medium",
      "Ibrahim's mother asks him to help her while he is playing with his friends. What is best?",
      ["Finish the game and then help",
       "Go and help her straight away",
       "Ask his friends to help instead",
       "Tell her he will help tomorrow"],
      1, "kids"),
    q("Qur'an Sciences", "medium",
      "Why did the scholars develop sciences such as asbab an-nuzul and hadith criticism?",
      ["To guard the texts and understand them rightly",
       "To record the history of the Arabian tribes",
       "To arrange the schools of Arabic grammar",
       "To count the letters and words of the Qur'an"],
      0),
    # ---- hard ----
    q("Tawheed & Qadar", "hard",
      "A trader plans carefully and takes every precaution, yet the deal still fails. Which "
      "understanding of qadar is correct?",
      ["The loss shows he was careless with du'a",
       "He should have relied only on his planning",
       "He took the means; the outcome is from Allah",
       "Taking the means removes the need for trust"],
      2, "adults"),
    q("Tawheed & Qadar", "hard",
      "Which statement agrees with the belief in al-qadar?",
      ["Only the good events are part of the decree",
       "People's choices fall outside Allah's will",
       "Allah's decree removes all responsibility",
       "Allah decreed all things, yet people choose"],
      3),
    q("Hadith Sciences", "hard",
      "A hadith reported at every level of its chain by a very large group of narrators is called:",
      ["Mawquf", "Ahad", "Mursal", "Mutawatir"],
      3, "adults"),
    q("Hadith Sciences", "hard",
      "Which grade of hadith sits between sahih and da'if?",
      ["Mursal", "Hasan", "Marfu'", "Gharib"],
      1, "adults"),
    q("Fiqh & Zakah", "hard",
      "A man's cash savings stayed above the nisab for two full years and he paid nothing. What "
      "must he do?",
      ["Pay the zakah for both of the years",
       "Pay only for the most recent year",
       "Pay half of it for each of the years",
       "Pay nothing, since the time has passed"],
      0, "adults"),
    q("Manners & Family", "hard",
      "A parent asks an adult child to take part in something clearly forbidden. What is the "
      "correct response?",
      ["Cut off all contact with them from now",
       "Obey them, since obedience comes first",
       "Decline kindly and still treat them well",
       "Obey them once, then repent to Allah"],
      2),
    # ---- added: audience balance ----
    q("Qur'an Sciences", "easy",
      "What does the word tafseer refer to?",
      ["The recording of the hadith",
       "The explanation of the Qur'an",
       "The reading with correct rules",
       "The counting of the verses"],
      1, "kids"),
    q("Manners & Family", "easy",
      "How should a Muslim speak to his parents when he does not agree with them?",
      ["Loudly, so that they hear",
       "Gently and with respect",
       "Only through an older brother",
       "By staying silent for days"],
      1, "kids"),
    q("Tawheed & Qadar", "medium",
      "Something bad happens to a Muslim. What should he believe about it?",
      ["It came about by pure chance",
       "It happened by Allah's decree",
       "It came from the stars above",
       "It shows Allah has left him"],
      1, "kids"),
    q("Hadith Sciences", "medium",
      "A child hears a story about the Prophet from a friend. What should he do before believing it?",
      ["Ask his friend to repeat it twice",
       "Write it down in his notebook",
       "Share it with the whole class",
       "Check that it is truly reported"],
      3, "kids"),
    q("Fiqh & Zakah", "medium",
      "On which of these is zakah due?",
      ["The house that he lives in",
       "The car that he drives daily",
       "The gold he keeps as savings",
       "The clothes that he wears"],
      2, "adults"),
    q("Hadith Sciences", "hard",
      "Two authentic hadith appear to conflict. What do the scholars do first?",
      ["Reject the weaker-sounding one",
       "Try to reconcile the two texts",
       "Follow the more famous scholar",
       "Set both of them aside for good"],
      1, "adults"),
]

# ===========================================================================
# STAGE 4 - Applied Islamic Knowledge   (kids L4, adults L3)
# Skills: Fiqh Rulings | Usul & Sources | Hadith Collections | Maqasid | Seerah
# ===========================================================================
IC_S4 = [
    # ---- easy ----
    q("Fiqh Rulings", "easy",
      "Which category covers an act a Muslim is rewarded for doing but not sinful for leaving?",
      ["Makruh", "Fard", "Mustahabb", "Haram"],
      2),
    q("Fiqh Rulings", "easy",
      "An act ruled makruh is one that is:",
      ["disliked, but not sinful to do",
       "forbidden, and punished if done",
       "required of every adult Muslim",
       "recommended, though not required"],
      0),
    q("Fiqh Rulings", "easy",
      "A friend offers Yusuf a drink that contains alcohol. Which ruling category does drinking it "
      "fall under?",
      ["Mustahabb", "Makruh", "Mubah", "Haram"],
      3, "kids"),
    q("Usul & Sources", "easy",
      "Which pair are the two primary sources of Islamic law?",
      ["The Sunnah and the ijma'", "The Qur'an and the Sunnah",
       "The qiyas and the ijma'", "The fatwa and the ijtihad"],
      1),
    q("Hadith Collections", "easy",
      "Which two of the six books are held to be the most authentic hadith collections?",
      ["Jami' at-Tirmidhi and Sunan Ibn Majah",
       "Sunan Abu Dawud and Sunan an-Nasa'i",
       "Sahih al-Bukhari and Sahih Muslim",
       "Muwatta Malik and Musnad Ahmad"],
      2, "kids"),
    q("Maqasid", "easy",
      "Which of these is one of the five aims of the shari'ah?",
      ["Protection of the homeland",
       "Protection of the language",
       "Protection of the marketplace",
       "Protection of the intellect"],
      3),
    q("Seerah", "easy",
      "What happened at the Ka'bah when the Muslims entered Makkah?",
      ["The idols inside it were removed",
       "The building of it was made larger",
       "The black stone was first placed",
       "The yearly hajj was begun there"],
      0, "kids"),
    # ---- medium ----
    q("Fiqh Rulings", "medium",
      "An act ruled mubah is one that is:",
      ["recommended, though not obliged",
       "permitted, with no reward or sin",
       "obliged on the community only",
       "forbidden except when in need"],
      1),
    q("Fiqh Rulings", "medium",
      "A duty described as fard kifayah is one that:",
      ["is left to the choice of each person",
       "must be performed by each and every adult Muslim",
       "becomes a duty only in the month of Ramadan",
       "is fulfilled for all if some carry it out"],
      3, "adults"),
    q("Usul & Sources", "medium",
      "When is qiyas used to reach a ruling?",
      ["When the scholars of a city agree upon a matter",
       "When the wording of a verse is unclear to readers",
       "When a new case shares the cause of a ruled case",
       "When a hadith is found to be weak in its chain"],
      2),
    q("Usul & Sources", "medium",
      "Modern intoxicating drugs are ruled forbidden by comparing them with wine. Which source is "
      "being used?",
      ["Ijma'", "Qiyas", "Naskh", "Tafseer"],
      1, "kids"),
    q("Usul & Sources", "medium",
      "Ijma' refers to the agreement of which group?",
      ["The qualified scholars of a generation",
       "The people of one town upon a custom",
       "The four imams upon every question",
       "The companions and their own children"],
      0, "adults"),
    q("Usul & Sources", "medium",
      "Ijtihad is best described as:",
      ["a trained scholar's effort to reach a ruling",
       "a personal opinion formed by any believer",
       "a ruling copied from the earlier scholars",
       "an agreement made between two of the schools"],
      0),
    q("Hadith Collections", "medium",
      "Why did the early scholars gather the hadith into written collections?",
      ["To record the lives of the Arab rulers",
       "To take the place of studying the Qur'an",
       "To settle the disputes between the tribes",
       "To preserve the Prophet's words accurately"],
      3, "kids"),
    q("Hadith Collections", "medium",
      "A student finds a hadith in one of the four Sunan books. What must he still check?",
      ["The city where it was written",
       "The grade the scholars gave it",
       "The number of words it holds",
       "The chapter it was placed in"],
      1, "adults"),
    q("Maqasid", "medium",
      "The prohibition of intoxicants most directly protects which aim of the shari'ah?",
      ["The lineage", "The wealth", "The intellect", "The religion"],
      2),
    q("Maqasid", "medium",
      "Ahmad finds a wallet full of money in the school corridor. What should he do with it?",
      ["Keep it, because he found it first",
       "Hand it in so the owner is found",
       "Share it with his closest friends",
       "Give it to any poor person he sees"],
      1, "kids"),
    q("Seerah", "medium",
      "How did the Prophet treat the people of Quraysh when the Muslims entered Makkah?",
      ["He pardoned them in general",
       "He drove them from the city",
       "He took all of their property",
       "He put their leaders in prison"],
      0, "kids"),
    q("Seerah", "medium",
      "What did the Treaty of Hudaybiyyah bring about for the Muslims?",
      ["The migration of Muslims to Abyssinia",
       "The immediate surrender of the Quraysh",
       "A time of peace in which Islam spread",
       "The building of the first masjid there"],
      2),
    # ---- hard ----
    q("Fiqh Rulings", "hard",
      "A man misses an obligatory prayer without excuse and prays extra voluntary prayers instead. "
      "What is the ruling?",
      ["Both are equal, as long as he prayed",
       "The voluntary covers the prayer he missed",
       "The missed prayer is wiped out by them",
       "The voluntary cannot take the place of it"],
      3, "adults"),
    q("Usul & Sources", "hard",
      "A matter is settled clearly by a verse of the Qur'an. What is the role of qiyas here?",
      ["It is used when the scholars disagree",
       "It is used to confirm the same ruling",
       "It replaces the text with a new ruling",
       "It is not used, as the text settles it"],
      3, "adults"),
    q("Hadith Collections", "hard",
      "Which of these is counted among the six well-known hadith books?",
      ["Musnad ash-Shafi'i", "Sunan Ibn Majah", "Sunan ad-Daraqutni", "Musannaf Abd ar-Razzaq"],
      1, "adults"),
    q("Maqasid", "hard",
      "The laws of inheritance and the prohibition of theft most directly protect which aim?",
      ["The wealth", "The life", "The intellect", "The religion"],
      0, "adults"),
    q("Seerah", "hard",
      "What did the Treaty of Hudaybiyyah allow the Muslims to do?",
      ["Keep whoever fled from the Quraysh",
       "Enter Makkah at once for that year",
       "Perform 'umrah in the following year",
       "End their treaties with other tribes"],
      2, "adults"),
    q("Seerah", "hard",
      "The allies of Quraysh attacked a tribe allied to the Muslims, breaking the treaty. What did "
      "the Prophet then do?",
      ["He sent them a letter asking for payment",
       "He signed a second treaty with them",
       "He marched on Makkah with the Muslims",
       "He moved the Muslims back to Madinah"],
      2),
    # ---- added: audience balance ----
    q("Fiqh Rulings", "easy",
      "Which category covers an act that every adult Muslim must carry out?",
      ["Mubah", "Fard", "Makruh", "Mustahabb"],
      1, "kids"),
    q("Seerah", "easy",
      "Which of these came first in the life of the Prophet?",
      ["The conquest of Makkah",
       "The farewell pilgrimage",
       "The Treaty of Hudaybiyyah",
       "The Prophet's last illness"],
      2, "kids"),
    q("Hadith Collections", "medium",
      "A report is found to be very weak in its chain. How should it be treated?",
      ["A ruling may still be taken from it",
       "It should be graded as sahih now",
       "No ruling should be taken from it",
       "It is stronger than a sahih hadith"],
      2, "kids"),
    q("Usul & Sources", "medium",
      "A Muslim with no training in fiqh meets a question he cannot answer. What should he do?",
      ["Give his own judgement on it",
       "Follow what his friends do",
       "Wait until all scholars agree",
       "Ask a qualified scholar about it"],
      3, "adults"),
    q("Usul & Sources", "hard",
      "A scholar gives one ruling in one country and another ruling elsewhere on the same question. "
      "What can explain this?",
      ["The Qur'an differs by country",
       "The custom and conditions differ",
       "One ruling must be mistaken",
       "Scholars may choose as they wish"],
      1, "adults"),
]
