# -*- coding: utf-8 -*-
"""Aqeedah, Fiqh and Hadith question pools."""

def q(skill, difficulty, prompt, options, correct, audience="both"):
    return dict(skill=skill, difficulty=difficulty, prompt=prompt, options=options,
                correct=correct, audience=audience, arabic=None)


# =========================================================================
# AQEEDAH — STAGE 1 : Foundations of Belief
# =========================================================================
AQ_S1 = [
    q("Pillars of Iman", "easy",
      "How many pillars of iman (faith) are there?",
      ["Four", "Five",
       "Six", "Seven"], 2),
    q("Pillars of Iman", "easy",
      "Which of these is one of the six pillars of iman?",
      ["Giving zakah to the poor", "Praying five times a day",
       "Fasting the month of Ramadan", "Believing in the angels"], 3, "kids"),
    q("Pillars of Iman", "medium",
      "A man believes in Allah, His angels, His books and His messengers, but says the Day of Judgement will never come. He has:",
      ["Denied a pillar of iman", "Kept his iman complete",
       "Weakened his iman slightly", "Committed one minor sin"], 0),
    q("Pillars of Iman", "medium",
      "A Muslim says: 'What reached me could never have missed me.' Which pillar of iman is he expressing?",
      ["Belief in the angels", "Belief in the books",
       "Belief in the Last Day", "Belief in al-qadar"], 3, "adults"),
    q("Pillars of Iman", "hard",
      "The pillars of iman are matters of the heart, while the pillars of Islam are mainly:",
      ["Beliefs held in the heart", "Rules kept by scholars only",
       "Words said once a year", "Deeds the limbs carry out"], 3),

    q("Belief in Allah", "easy",
      "Amina asks her teacher what 'tawheed' means. Which answer is correct?",
      ["Worshipping Allah alone, with no partner", "Loving the Prophet more than anyone",
       "Following the five pillars of Islam", "Learning the names of the prophets"], 0, "kids"),
    q("Belief in Allah", "medium",
      "Muslims believe that Allah's knowledge:",
      ["Covers deeds but not thoughts", "Includes all that was and will be",
       "Is shared with the angels", "Grows as events happen"], 1),
    q("Belief in Allah", "hard",
      "The words 'la ilaha illa Allah' mean:",
      ["No one creates except Allah", "No one is worshipped rightly except Allah",
       "No one is a messenger except by Allah", "No one is remembered except Allah"], 1),
    q("Belief in Allah", "medium",
      "A child asks who made Allah. The correct answer is:",
      ["No one made Allah; He has always existed", "Allah made Himself before the world",
       "We will only find out on the Last Day", "The angels were made first, then Allah"], 0, "kids"),

    q("Angels and Books", "easy",
      "The angels were created from:",
      ["Clay", "Light",
       "Fire", "Water"], 1, "kids"),
    q("Angels and Books", "medium",
      "Which book was given to Prophet Musa?",
      ["The Injeel", "The Zaboor",
       "The Tawrah", "The Qur'an"], 2),
    q("Angels and Books", "medium",
      "Which angel brought the revelation to the prophets?",
      ["Jibreel", "Malik",
       "Mika'eel", "Israfeel"], 0, "kids"),
    q("Angels and Books", "hard",
      "What do Muslims believe about the earlier scriptures today?",
      ["They are followed with the Qur'an", "They were invented, not revealed",
       "They were revealed, but later changed", "They are kept exactly as revealed"], 2),
    q("Angels and Books", "medium",
      "Which statement about the angels is correct?",
      ["They obey Allah and never disobey", "They marry and have children",
       "They sometimes disobey and repent", "They are the souls of the righteous"], 0, "adults"),
    q("Angels and Books", "hard",
      "Belief in the angels means accepting that they:",
      ["Act as they wish without command", "Are real creatures hidden from us",
       "Are a symbol of good thoughts", "Are the spirits of dead prophets"], 1, "adults"),

    q("Prophets", "easy",
      "Which one of these was a prophet?",
      ["Jibreel", "Iblees",
       "Abu Bakr", "Nuh"], 3, "kids"),
    q("Prophets", "easy",
      "Abu Bakr as-Siddeeq was:",
      ["A prophet sent before Muhammad", "An angel who recorded deeds",
       "A companion of the Prophet", "A messenger sent to Egypt"], 2),
    q("Prophets", "medium",
      "Muhammad (peace be upon him) is called the Seal of the Prophets. This means:",
      ["He was the first prophet chosen", "He was sent to the Arabs only",
       "He sealed his letters with a ring", "No prophet will come after him"], 3),
    q("Prophets", "medium",
      "Muslims must believe that the messengers:",
      ["Conveyed Allah's message truthfully", "Were free of all human needs",
       "Knew the unseen at all times", "Shared in Allah's power to create"], 0, "adults"),
    q("Prophets", "hard",
      "A man says: 'I believe in Muhammad but not in Musa.' Islamically he:",
      ["Has believed in the books instead", "Has fulfilled belief, since Musa came earlier",
       "Has not fulfilled belief in the messengers", "Has made only a minor mistake"], 2),

    q("Last Day and Qadar", "easy",
      "What do Muslims believe happens on the Day of Judgement?",
      ["People are raised and questioned", "Everyone returns to live on earth again",
       "Only the righteous are raised again", "Only the prophets are raised again"], 0, "kids"),
    q("Last Day and Qadar", "medium",
      "Belief in al-qadar means believing that:",
      ["People have no choice in anything", "Allah knows and decrees all things",
       "Good is decreed but evil is not", "Events simply happen by chance"], 1),
    q("Last Day and Qadar", "medium",
      "A man plans carefully, works hard, then says: 'The result is with Allah.' This is:",
      ["Wrong; planning denies qadar", "Wrong; trust means leaving the means",
       "Correct; he takes means and trusts", "Correct only if he succeeds"], 2, "adults"),
    q("Last Day and Qadar", "easy",
      "Sara's team lost the match although she tried her best. What should she believe?",
      ["Losing shows Allah is angry", "Allah decreed it, and knows best",
       "Allah did not hear her du'a", "Her du'a was wasted this time"], 1, "kids"),
    q("Last Day and Qadar", "hard",
      "A man refuses a dishonest profit. Which answer shows belief in the Last Day?",
      ["'Nobody would ever find out'", "'It would harm my reputation'",
       "'The law of the land forbids it'", "'I will be asked about my wealth'"], 3, "adults"),
]


# =========================================================================
# AQEEDAH — STAGE 2 : Applied Aqeedah
# =========================================================================
AQ_S2 = [
    q("Categories of Tawheed", "easy",
      "Which of these should be asked for from Allah alone?",
      ["Help lifting a heavy box", "Forgiveness of sins",
       "A pencil from a classmate", "Directions to the masjid"], 1, "kids"),
    q("Categories of Tawheed", "medium",
      "Saying 'Allah alone sends the rain and provides sustenance' affirms:",
      ["Belief in the revealed books", "Tawheed al-uloohiyyah",
       "Tawheed ar-ruboobiyyah", "Tawheed al-asma wa as-sifat"], 2),
    q("Categories of Tawheed", "medium",
      "Affirming that Allah is As-Samee' (the All-Hearing) without asking how belongs to:",
      ["Tawheed al-asma wa as-sifat", "Tawheed ar-ruboobiyyah",
       "Tawheed al-uloohiyyah", "Belief in al-qadar"], 0),
    q("Categories of Tawheed", "medium",
      "A man believes Allah alone creates and sustains, yet he calls on a dead saint for help. What is he missing?",
      ["Belief in the Last Day", "Belief in the angels",
       "Tawheed ar-ruboobiyyah", "Tawheed al-uloohiyyah"], 3, "adults"),
    q("Categories of Tawheed", "hard",
      "Which of these is an act of worship that may not be directed to anyone besides Allah?",
      ["Naming a child after the righteous", "Standing to greet a guest",
       "Giving a gift to a neighbour", "Making a vow (nadhr)"], 3),

    q("Shirk", "easy",
      "Yusuf wears a string on his wrist believing the string keeps bad luck away. This is:",
      ["Sunnah, taught by the Prophet", "Makruh, disliked but allowed",
       "Shirk, trusting other than Allah", "Mubah, allowed for children"], 2, "kids"),
    q("Shirk", "easy",
      "A friend says: 'Touch this stone for luck before the exam.' What should a Muslim do?",
      ["Refuse, because good comes from Allah", "Touch it once, then make du'a",
       "Touch it without believing in it", "Ask a teacher to touch it"], 0, "kids"),
    q("Shirk", "medium",
      "Doing a good deed so that people will praise you is called:",
      ["Kufr, plain disbelief", "Nifaq akbar, major hypocrisy",
       "Bid'ah, an innovation", "Riya, a form of minor shirk"], 3),
    q("Shirk", "medium",
      "Swearing an oath by other than Allah, such as by one's father, is:",
      ["Minor shirk", "Recommended when serious",
       "Major shirk", "Permitted with no blame"], 0),
    q("Shirk", "hard",
      "Which of these is major shirk?",
      ["Wearing a ring to bring luck", "Swearing by other than Allah",
       "Slaughtering for other than Allah", "Saying 'what Allah and you willed'"], 2, "adults"),
    q("Shirk", "medium",
      "Which phrase should replace 'what Allah and you willed'?",
      ["'What we together willed'", "'What Allah willed, then you willed'",
       "'What you willed, then Allah willed'", "'What Allah and you both willed'"], 1, "adults"),
    q("Shirk", "hard",
      "Calling on a righteous dead person to intercede is rejected mainly because:",
      ["Only prophets may be called upon", "Du'a is worship, due to Allah alone",
       "It is allowed only inside a masjid", "The dead hear no sound at all"], 1),

    q("Names and Attributes", "medium",
      "Muslims affirm Allah's attributes without likening them to creation because:",
      ["The attributes are only metaphors", "Attributes belong to creation alone",
       "Only the angels know their meaning", "Nothing in creation is like Allah"], 3),
    q("Names and Attributes", "easy",
      "Can we picture what Allah looks like?",
      ["Yes, like a bright light", "No, nothing is like Allah",
       "Yes, like a kind old man", "Yes, like the wide sky"], 1, "kids"),
    q("Names and Attributes", "hard",
      "A Muslim reads a verse mentioning the Hand of Allah. The correct position is:",
      ["Avoid reading such verses", "Affirm it as befits Allah",
       "Deny it as pure metaphor", "Picture it like a human hand"], 1, "adults"),
    q("Signs of the Hour", "easy",
      "The minor signs of the Hour differ from the major signs in that they:",
      ["Happen only in Makkah and Madinah", "Are known to the scholars alone",
       "Take place after the Hour begins", "Appear gradually before the major ones"], 3),
    q("Names and Attributes", "hard",
      "The names of Allah are:",
      ["Known only from the Qur'an and Sunnah", "Chosen by the scholars of each age",
       "Different in every school of fiqh", "Limited to exactly ninety-nine"], 0),

    q("Shirk", "easy",
      "Who should a Muslim ask to cure him when he falls ill?",
      ["Allah, while taking the medicine", "A charm worn on the arm",
       "A star seen in the sky", "The doctor alone, not Allah"], 0, "kids"),

    q("Qadar Applied", "medium",
      "A man is wronged by someone else's mistake. Belief in qadar means that he:",
      ["Must never ask for his right", "May still ask for his right",
       "Should blame the decree itself", "Must say it was not decreed"], 1),
    q("Qadar Applied", "medium",
      "After a business loss, which response fits belief in qadar?",
      ["Insist that Allah did not know it", "Stop working, since all is decreed",
       "Accept Allah's decree and plan again", "Say the loss was only bad luck"], 2, "adults"),
    q("Qadar Applied", "hard",
      "Saying 'if only I had done that, this would not have happened' after a calamity is discouraged because:",
      ["It counts as major shirk", "It denies that Allah exists",
       "It opens the door to shaytan", "It cancels all earlier good deeds"], 2),

    q("Signs of the Hour", "easy",
      "Who knows exactly when the Last Day will come?",
      ["Allah alone knows it", "Jibreel was told the date",
       "The scholars can work it out", "The Prophet told his family"], 0, "kids"),
    q("Signs of the Hour", "medium",
      "Which of these is a major sign of the Hour?",
      ["The spread of ignorance", "The increase of earthquakes",
       "The coming of the Dajjal", "Competing in tall buildings"], 2),
    q("Signs of the Hour", "medium",
      "The descent of 'Isa (peace be upon him) is:",
      ["A major sign of the Hour", "A minor sign already passed",
       "A yearly event in Ramadan", "A sign known to angels only"], 0),
    q("Signs of the Hour", "hard",
      "Which pair are both major signs of the Hour?",
      ["Ad-Dajjal and the spread of riba", "Earthquakes and the beast of the earth",
       "The loss of trust and the smoke", "Ad-Dajjal and Ya'juj and Ma'juj"], 3, "adults"),
]


# =========================================================================
# FIQH — STAGE 1 : Foundations of Worship
# =========================================================================
FQ_S1 = [
    q("Wudu", "easy",
      "Which of these breaks wudu?",
      ["Cutting your nails", "Eating a meal",
       "Drinking milk", "Passing urine"], 3, "kids"),
    q("Wudu", "easy",
      "Which of these is a required part of wudu?",
      ["Washing the hands to the wrists", "Washing the face",
       "Wiping the neck", "Using the siwak"], 1),
    q("Wudu", "medium",
      "In wudu, the face is washed and then:",
      ["The head is wiped", "The arms are washed",
       "The feet are washed", "The ears are wiped"], 1),
    q("Wudu", "medium",
      "A man makes wudu, then falls into a deep sleep. Before praying he must:",
      ["Make a full ghusl", "Perform tayammum instead",
       "Pray without repeating wudu", "Make his wudu again"], 3, "adults"),
    q("Wudu", "hard",
      "Which of these certainly invalidates wudu?",
      ["Bleeding from a small cut", "Passing wind",
       "Vomiting a mouthful", "Touching one's wife's hand"], 1, "adults"),

    q("Purity", "easy",
      "Before praying, a Muslim's clothes and place must be:",
      ["Clean from impurity", "White in colour",
       "Perfumed with musk", "New and expensive"], 0, "kids"),
    q("Purity", "medium",
      "Ahmad's shirt has dried mud on it. May he pray in it?",
      ["Yes, mud itself is not impure", "Only if he changes his shirt",
       "No, all dirt is impure", "Only if he washes it twice"], 0, "kids"),
    q("Purity", "medium",
      "A full ghusl becomes obligatory after:",
      ["Eating any kind of meat", "Deep sleep at night",
       "Touching a dog's fur", "Sexual discharge (janabah)"], 3),
    q("Purity", "medium",
      "Which of these is impure (najis) and must be washed off before prayer?",
      ["Urine", "Sweat",
       "Tears", "Saliva"], 0, "adults"),

    q("Salah", "easy",
      "How many obligatory prayers are there each day?",
      ["Three", "Four",
       "Five", "Six"], 2),
    q("Salah", "easy",
      "How many rak'ah are there in the fard of Maghrib?",
      ["Two", "Three",
       "Four", "Five"], 1, "kids"),
    q("Salah", "medium",
      "Sami comes home late and prays 'Isha alone. How many fard rak'ah does he pray?",
      ["Two", "Three",
       "Four", "Five"], 2),
    q("Salah", "medium",
      "The time of the Fajr prayer ends at:",
      ["Sunset", "Midnight",
       "Sunrise", "Midday"], 2),
    q("Salah", "medium",
      "Which of these invalidates the prayer?",
      ["Stepping across to fill a gap", "Reciting quietly to oneself",
       "Closing the eyes for a moment", "Speaking deliberately during it"], 3),
    q("Salah", "medium",
      "Layla begins praying and remembers that she has no wudu. She should:",
      ["Stop, make wudu, and pray again", "Carry on and repeat it tomorrow",
       "Ask someone to pray for her", "Finish it, then make wudu"], 0, "kids"),
    q("Salah", "hard",
      "A traveller cannot work out the qiblah and nobody can guide him. He should:",
      ["Wait until he is certain of it", "Judge his best and pray",
       "Face the east in every land", "Leave it until he returns"], 1, "adults"),
    q("Salah", "hard",
      "A man oversleeps and misses 'Asr. He should:",
      ["Pray it as soon as he wakes", "Skip it and pray Maghrib",
       "Pray it twice the next day", "Give charity in its place"], 0),
    q("Salah", "hard",
      "Which of these is a condition to be met before the prayer begins?",
      ["Reciting at-tashahhud", "Bowing with calmness",
       "Purity from impurity", "Saying the final tasleem"], 2, "adults"),

    q("Fasting", "easy",
      "Fasting in Ramadan means not eating or drinking:",
      ["From sunset until dawn", "From sunrise until sunset",
       "From dawn until sunset", "From midnight until noon"], 2, "kids"),
    q("Fasting", "medium",
      "Nadia forgets that she is fasting and eats a biscuit. Her fast:",
      ["Is valid only for young girls", "Is broken; she stops for the day",
       "Is still valid; she carries on", "Is broken; she owes two months"], 2, "kids"),
    q("Fasting", "medium",
      "Which of these breaks the fast?",
      ["Eating deliberately", "Rinsing the mouth",
       "Brushing the teeth", "Taking a shower"], 0, "adults"),
    q("Fasting", "hard",
      "Fasting Ramadan is obligatory on every Muslim who is:",
      ["Adult, sane and able", "Male and above forty",
       "Living in a Muslim land", "Free of any daily work"], 0),

    q("Zakah", "easy",
      "Zakah is:",
      ["A payment due in Ramadan", "A gift given to friends",
       "A tax paid to any state", "A pillar of Islam"], 3),
    q("Zakah", "medium",
      "Zakah is given to:",
      ["Anyone who asks for it first", "The poor and the needy",
       "Rich relatives as a gift", "The imam to keep for himself"], 1, "kids"),
    q("Zakah", "medium",
      "Zakah is due on:",
      ["The house the family lives in", "Wages on the day they are paid",
       "Furniture used in the home", "Wealth kept for a full year"], 3, "adults"),
    q("Zakah", "hard",
      "A wealthy man refuses to pay zakah although he knows it is due. This is:",
      ["Allowed if he gives later", "Only disliked (makruh)",
       "A matter of personal choice", "A major sin"], 3),
]


# =========================================================================
# FIQH — STAGE 2 : Applied Fiqh & Daily Life
# =========================================================================
FQ_S2 = [
    q("Rulings (Ahkam)", "easy",
      "An action that is disliked, but carries no sin if done, is:",
      ["Haram", "Mubah",
       "Makruh", "Wajib"], 2),
    q("Rulings (Ahkam)", "medium",
      "A worker chooses rice rather than bread for his lunch. This choice is:",
      ["Mubah", "Wajib",
       "Sunnah", "Makruh"], 0, "adults"),
    q("Rulings (Ahkam)", "easy",
      "Saying 'Bismillah' before eating is a sunnah. If Zayd forgets to say it, he has:",
      ["To fast the following day", "Missed a reward, with no sin",
       "Committed a sin to repent from", "To start his meal again"], 1, "kids"),
    q("Rulings (Ahkam)", "hard",
      "A man is starving and the only food he can find is pork. Eating it is:",
      ["Recommended to save life", "Disliked but still rewarded",
       "Permitted by necessity", "Forbidden in every case"], 2, "adults"),
    q("Rulings (Ahkam)", "hard",
      "Which of these is fard kifayah, an obligation that lapses when enough people do it?",
      ["The funeral prayer", "Paying the zakah",
       "The Friday prayer", "Fasting Ramadan"], 0),

    q("Zakah", "easy",
      "The rate of zakah on saved money is:",
      ["2.5%", "5%",
       "10%", "20%"], 0),
    q("Zakah", "medium",
      "Zakah falls due once wealth reaches the nisab and is held for:",
      ["One solar year", "Two lunar years",
       "Six lunar months", "One lunar year"], 3, "adults"),
    q("Zakah", "medium",
      "The nisab for zakah on money is measured against:",
      ["The average wage", "The price of wheat",
       "The cost of housing", "Gold or silver"], 3),
    q("Zakah", "medium",
      "Which of these people may be given zakah?",
      ["A relative who is already wealthy", "A rich neighbour who asks for it",
       "The donor's own dependent child", "A traveller stranded without money"], 3, "adults"),
    q("Zakah", "hard",
      "A man has savings of 10,000 above the nisab, held for a full lunar year. His zakah is:",
      ["100", "250",
       "500", "1,000"], 1, "adults"),
    q("Zakah", "hard",
      "Zakah may NOT be given to:",
      ["One's own parents", "A student in debt",
       "A stranded traveller", "A poor stranger"], 0),

    q("Travel and Illness", "easy",
      "Omar's family drive a long distance to a wedding. At Dhuhr time they may pray:",
      ["One rak'ah only", "Three rak'ah instead of four",
       "Two rak'ah instead of four", "Four rak'ah as usual"], 2, "kids"),
    q("Travel and Illness", "medium",
      "Which prayers are NOT shortened by a traveller?",
      ["Maghrib and Fajr", "Dhuhr and 'Asr",
       "'Asr and 'Isha", "Dhuhr and 'Isha"], 0, "adults"),
    q("Travel and Illness", "medium",
      "Hana's family are driving all day and pray Dhuhr and 'Asr together. This is called:",
      ["Nafl, extra prayers", "Qada, making up prayers",
       "Jam', joining the prayers", "Qasr, shortening the prayers"], 2, "kids"),
    q("Travel and Illness", "medium",
      "A man travels a long journey in Ramadan and finds fasting hard. He may:",
      ["Break the fast and make up the days", "Break the fast and pay money only",
       "Miss the days with no make-up", "Fast half a day and then stop"], 0, "adults"),
    q("Travel and Illness", "medium",
      "An elderly man is permanently unable to fast. Instead of fasting he should:",
      ["Make up the days when able", "Fast in the winter months only",
       "Pay double zakah that year", "Feed a poor person for each day"], 3, "adults"),
    q("Travel and Illness", "medium",
      "A woman does not fast some days of Ramadan because of menstruation. She must:",
      ["Feed the poor in their place", "Do nothing; they are excused",
       "Make up those days later", "Fast them in Ramadan anyway"], 2, "adults"),
    q("Travel and Illness", "hard",
      "A traveller joins a resident imam who is praying four rak'ah. The traveller should:",
      ["Repeat the prayer afterwards", "Pray only two, then leave",
       "Complete four with the imam", "Pray alone so he can shorten"], 2, "adults"),

    q("Tayammum", "easy",
      "Tayammum is performed using:",
      ["A damp cloth only", "Clean earth or dust",
       "Warm soapy water", "Sand mixed with water"], 1, "kids"),
    q("Tayammum", "medium",
      "Tayammum takes the place of wudu when:",
      ["The water is a little cold", "No water can be found or used",
       "One is in a hurry to pray", "One is tired after work"], 1),
    q("Tayammum", "medium",
      "In tayammum, which parts are wiped?",
      ["The head and the arms", "The face and the hands",
       "The hands and the feet", "The face and the feet"], 1, "kids"),
    q("Tayammum", "hard",
      "A man prays with tayammum and finds water only after finishing. His prayer:",
      ["Counts as a voluntary prayer", "Is valid and is not repeated",
       "Must be repeated with wudu", "Is valid only when travelling"], 1),

    q("Halal Earnings", "easy",
      "Taking interest (riba) on a loan is:",
      ["Makruh", "Mubah",
       "Sunnah", "Haram"], 3),
    q("Halal Earnings", "medium",
      "A shopkeeper hides a fault in the goods he sells. This sale is:",
      ["Deception, and the profit is unlawful", "Valid, since the price was agreed",
       "Allowed, as the buyer should check", "Disliked, but the profit is lawful"], 0, "adults"),
    q("Halal Earnings", "easy",
      "Bilal finds a wallet in the school yard. He should:",
      ["Share the money with his friends", "Give it away as charity at once",
       "Keep it, since he found it first", "Hand it in so the owner can claim it"], 3, "kids"),
    q("Halal Earnings", "medium",
      "A worker finishes the job he agreed to do. His employer must:",
      ["Reduce it for small mistakes", "Pay in goods instead of money",
       "Pay the agreed wage without delay", "Delay when business is slow"], 2),
]


# =========================================================================
# HADITH — STAGE 1 : Hadith Foundations
# =========================================================================
HD_S1 = [
    q("Hadith Basics", "easy",
      "A hadith is:",
      ["A du'a said after the prayer", "A report of the Prophet's words",
       "A chapter of the Qur'an", "A ruling written by a judge"], 1),
    q("Hadith Basics", "easy",
      "Zayd wants to know how the Prophet greeted people. Where should he look?",
      ["In an Arabic dictionary", "In the books of hadith",
       "In a history of Egypt", "In a book of poetry"], 1, "kids"),
    q("Hadith Basics", "medium",
      "Which of these is recited in salah as the speech of Allah?",
      ["A saying of the companions", "A hadith about intentions",
       "A du'a taught by Abu Bakr", "Surah al-Fatihah"], 3),
    q("Hadith Basics", "hard",
      "In a hadith qudsi the meaning is from Allah, while the wording is:",
      ["From the companion narrating", "From the scholar recording",
       "From the Prophet himself", "From the Qur'an directly"], 2, "adults"),
    q("Hadith Basics", "hard",
      "Which of these is a saying of the Prophet, not a verse of the Qur'an?",
      ["'Say: He is Allah, the One'", "'And establish the prayer'",
       "'Read in the name of your Lord'", "'The believers are like one body'"], 3),
    q("Hadith Basics", "hard",
      "Why do Muslims need the sunnah alongside the Qur'an?",
      ["It is recited in place of the Qur'an", "It shows how its commands are carried out",
       "It replaces rulings found in the Qur'an", "It was revealed before the Qur'an"], 1),
    q("Hadith Basics", "hard",
      "A saying is passed around as the Prophet's words, but nobody can trace it to him. It should be:",
      ["Written into books of du'a", "Not ascribed to him until it is checked",
       "Accepted, since its meaning is good", "Repeated as a hadith in gatherings"], 1, "adults"),

    q("The Sunnah", "medium",
      "The sunnah is the Prophet's sayings, his actions, and:",
      ["His family's opinions after him", "The customs of his own tribe",
       "The laws of the earlier nations", "His approval of what others did"], 3),
    q("The Sunnah", "medium",
      "The companions sat while eating because the Prophet did. Following his actions is:",
      ["Adding to the religion", "Following the sunnah",
       "A rule for Arabs only", "Something only imams do"], 1, "kids"),
    q("The Sunnah", "hard",
      "A companion did something in front of the Prophet and he watched without objecting. This is:",
      ["A personal opinion (ra'y)", "A rejected innovation",
       "A verse of revelation", "A tacit approval (taqrir)"], 3, "adults"),
    q("The Sunnah", "easy",
      "When the Prophet's name is mentioned, a Muslim says:",
      ["Peace be upon him", "Praise be to Allah",
       "Glory be to Allah", "Allah is the Greatest"], 0, "kids"),
    q("The Sunnah", "medium",
      "Following the sunnah in acts of worship means:",
      ["Choosing whatever is easiest", "Leaving them to local custom",
       "Doing them as the Prophet taught", "Adding what suits us today"], 2, "adults"),
    q("The Sunnah", "hard",
      "A practice with no basis in the Qur'an or the sunnah is performed as worship. It is:",
      ["A necessity (darurah)", "A permitted custom ('urf)",
       "An innovation (bid'ah)", "A recommended act (mandub)"], 2),

    q("Famous Hadith", "easy",
      "The hadith 'Actions are judged by intentions' teaches that:",
      ["Intentions must be said aloud", "What is in the heart matters",
       "Only big actions are counted", "Deeds done in public are best"], 1, "kids"),
    q("Famous Hadith", "medium",
      "'None of you truly believes until he loves for his brother what he loves for himself' teaches:",
      ["Loving your own family first", "Praying for yourself before others",
       "Giving away all of your wealth", "Wishing others the good you want"], 3),
    q("Famous Hadith", "medium",
      "'The best of you are those who learn the Qur'an and teach it' shows that:",
      ["Learning it ends other duties", "Reciting quickly is the aim",
       "Teaching the Qur'an is rewarded", "Only scholars may read it"], 2, "adults"),
    q("Famous Hadith", "medium",
      "'Removing something harmful from the road is charity.' Hana sees broken glass on the path. She should:",
      ["Move it away safely", "Walk around it quietly",
       "Say nothing to anybody", "Wait for an adult to pass"], 0, "kids"),
    q("Famous Hadith", "medium",
      "'Whoever believes in Allah and the Last Day should speak good or keep silent' teaches that:",
      ["Guarding the tongue is part of iman", "Silence is better than praying",
       "Speaking is disliked for Muslims", "Only scholars are allowed to speak"], 0),
    q("Famous Hadith", "medium",
      "'Whoever does not thank people has not thanked Allah.' At home this means Sami should:",
      ["Thank guests but not family", "Thank Allah in du'a only",
       "Thank his mother for her help", "Stay silent to be humble"], 2, "kids"),

    q("Hadith Compilers", "easy",
      "Which of these is a famous collection of hadith?",
      ["Surah al-Baqarah", "Tafsir al-Jalalayn",
       "Al-Muwafaqat", "Sahih al-Bukhari"], 3),
    q("Hadith Compilers", "easy",
      "Sahih Muslim was compiled by:",
      ["Muslim ibn al-Hajjaj", "Abu Dawud as-Sijistani",
       "Malik ibn Anas", "Muhammad al-Bukhari"], 0, "adults"),
    q("Hadith Compilers", "medium",
      "The famous collection of Imam Malik is called:",
      ["Al-Mustadrak", "Al-Musnad",
       "Al-Muwatta", "As-Sunan"], 2, "adults"),
    q("Hadith Compilers", "medium",
      "The hadith collection of Imam Ahmad ibn Hanbal is known as:",
      ["Al-Jami'", "Al-Mustadrak",
       "Al-Musnad", "Al-Muwatta"], 2),
    q("Hadith Compilers", "medium",
      "Who first memorised the Prophet's hadith and passed them on?",
      ["The companions who heard him", "Scholars living in our time",
       "The kings of the Arab lands", "Travellers from distant lands"], 0, "kids"),
]


# =========================================================================
# HADITH — STAGE 2 : Hadith Sciences
# =========================================================================
HD_S2 = [
    q("Isnad and Matn", "easy",
      "In a hadith, the people who passed the report on one after another are called:",
      ["The tarjamah", "The isnad",
       "The matn", "The tafsir"], 1, "kids"),
    q("Isnad and Matn", "easy",
      "'Umar reported that the Prophet said: 'Actions are by intentions.' The reported words themselves are:",
      ["The isnad", "The takhrij",
       "The tabaqat", "The matn"], 3),
    q("Isnad and Matn", "hard",
      "Why does a sound chain matter?",
      ["It makes the wording easier to memorise", "It shortens the text for teaching",
       "It proves the book is very old", "It shows the report reaches the Prophet"], 3),
    q("Isnad and Matn", "medium",
      "Two narrations of one event differ in wording but agree in meaning. This is known as:",
      ["Narration by meaning (bil-ma'na)", "Proof that the chain is broken",
       "Evidence that it is mutawatir", "A sign that both are fabricated"], 0),
    q("Isnad and Matn", "medium",
      "'Ilm al-jarh wa at-ta'dil is the science of:",
      ["Explaining difficult wording", "Counting the chapters of books",
       "Reciting hadith with tajweed", "Weighing the narrators' reliability"], 3, "adults"),
    q("Isnad and Matn", "easy",
      "A hadith that is fully accepted must be sound in:",
      ["Its chain only", "Its text only",
       "Both its chain and its text", "Its book title and chapter"], 2),

    q("Hadith Grading", "medium",
      "Which grade is given to a hadith with a connected chain of trustworthy, precise narrators?",
      ["Da'if", "Mawdu'",
       "Sahih", "Hasan"], 2),
    q("Hadith Grading", "medium",
      "A hadith is like the sahih except that one narrator is slightly less precise. It is graded:",
      ["Mutawatir", "Sahih",
       "Hasan", "Mawdu'"], 2),
    q("Hadith Grading", "medium",
      "A student finds a hadith whose chain is missing a narrator. It is:",
      ["Hasan", "Da'if",
       "Mutawatir", "Sahih"], 1, "adults"),
    q("Hadith Grading", "hard",
      "A report is traced back to a narrator who admitted inventing it. It is graded:",
      ["Mawdu', fabricated", "Ahad, single-chained",
       "Da'if, weak", "Hasan, good"], 0, "adults"),
    q("Hadith Grading", "easy",
      "The teacher says that a hadith is da'if. This means that the hadith is:",
      ["Widely reported", "Weak", "Strong", "Invented"], 1, "kids"),
    q("Hadith Grading", "medium",
      "If one man in the chain was known to lie, the hadith is:",
      ["Not accepted", "Still accepted",
       "Made stronger", "Named mutawatir"], 0, "kids"),
    q("Hadith Grading", "hard",
      "A weak hadith is also reported through several other independent weak routes. It may be raised to:",
      ["Mawdu' mashhur", "Hasan li-ghayrihi",
       "Sahih li-dhatihi", "Mutawatir lafzi"], 1),

    q("Mutawatir and Ahad", "medium",
      "A hadith reported in every generation by so many that they could not agree on a lie is:",
      ["Mutawatir", "Ahad",
       "Hasan", "Mursal"], 0),
    q("Mutawatir and Ahad", "medium",
      "Most of the hadith found in the books of sunnah are:",
      ["Mutawatir reports", "Hadith qudsi",
       "Sayings of companions", "Ahad reports"], 3, "adults"),

    q("The Six Books", "easy",
      "Which two collections are known as the Sahihayn?",
      ["An-Nasa'i and Ibn Majah", "Ahmad and Malik",
       "Al-Bukhari and Muslim", "Abu Dawud and at-Tirmidhi"], 2, "kids"),
    q("The Six Books", "medium",
      "Besides the Sahihayn, the six books are the collections of:",
      ["Abu Dawud, at-Tirmidhi, an-Nasa'i and Ibn Majah", "Ahmad, al-Hakim, at-Tabarani and al-Bazzar",
       "Al-Bayhaqi, ad-Daraqutni, Malik and Ahmad", "Malik, Ahmad, ad-Darimi and al-Bayhaqi"], 0, "adults"),
    q("The Six Books", "easy",
      "Which collection is NOT one of the six books?",
      ["Jami' at-Tirmidhi", "Sunan Abu Dawud",
       "Sunan an-Nasa'i", "Al-Muwatta of Malik"], 3),
    q("The Six Books", "hard",
      "Al-Bukhari and Muslim are ranked as the most authentic collections because their authors:",
      ["Travelled the furthest to collect them", "Set the strictest conditions for accepting",
       "Wrote the largest number of volumes", "Lived nearest to the Prophet's own time"], 1),

    q("Applying Grades", "hard",
      "A speaker likes a narration, but the scholars grade it mawdu'. He should:",
      ["Quote it with the word 'reportedly'", "Keep it for children's lessons",
       "Drop it and not quote it as hadith", "Use it, since its meaning is good"], 2, "adults"),
    q("Applying Grades", "hard",
      "Which use of a da'if hadith is agreed to be wrong?",
      ["Mentioning it and stating its weakness", "Studying it in a class on hadith terms",
       "Comparing it with stronger reports", "Establishing a ruling of halal or haram"], 3, "adults"),
    q("Applying Grades", "medium",
      "Amina hears a story about the Prophet from a friend. She should first:",
      ["Write it in her notebook as true", "Add a nicer ending to it",
       "Check it with a teacher or a book", "Pass it on to everybody at once"], 2, "kids"),
    q("The Six Books", "easy",
      "A hadith reported by both al-Bukhari and Muslim is described as:",
      ["Mursal (the chain is cut)", "Mawqoof (stops at a companion)",
       "Muttafaq 'alayh (agreed upon)", "Shadh (odd and contradicting)"], 2),
    q("Applying Grades", "medium",
      "Sami wants to put a hadith on the class noticeboard. He should choose one that is:",
      ["Short and easy to read", "New to all his classmates",
       "Popular on the internet", "Graded authentic by scholars"], 3, "kids"),
    q("Applying Grades", "hard",
      "A hadith reaches us with one sahih chain and, by another route, a hasan chain. Scholars treat it as:",
      ["Fabricated by later narrators", "Established as authentic",
       "Rejected as contradictory", "Weak, because the routes differ"], 1),
]
